### ISSUE TITLE
 why still pop up "No module named 'markdown' "?

### ISSUE THREAD

**Issue by ymbrite** [theacodes/blog.thea.codes#11]
hi.

$ git clone https://github.com/theacodes/blog.thea.codes
$ cd blog.thea.codes
$ pip3 install -r requirements.txt
$ python3 build.py
Traceback (most recent call last):
  File "C:\Users\12799\blog.thea.codes\build.py", line 5, in <module>
    import markdown
ModuleNotFoundError: No module named 'markdown'
$ pip3 install markdown
Requirement already satisfied: markdown in c:\python312\lib\site-packages (3.7)

$ python3 build.py
Traceback (most recent call last):
  File "C:\Users\12799\blog.thea.codes\build.py", line 5, in <module>
    import markdown
ModuleNotFoundError: No module named 'markdown'

why still pop up "No module named 'markdown' "?
thank you for your reply!

**Comment by theacodes** [comment]
... Why are you trying to build my blog anyway?

**Comment by ymbrite** [comment]
hi.
well,i try to learn python coding.
can u reply me?
tks a lot

**Comment by brightmann** [comment]
i know how to fix it.
enter a virtualenv,then the issue disappeared.
but i visit ur site blog.thea.codes, how to implement pagination?

**Comment by theacodes** [comment]
There is no pagination. If you want to learn Python, I wouldn't suggest working with my undocumented build tool for my personal site and blog.
