### ISSUE TITLE
no I2C output

### ISSUE THREAD

**Issue by DFCurry** [theacodes/blog.thea.codes#2]
Hello.  Thank you for posting https://blog.thea.codes/understanding-the-sam-d21-clocks/  That is, by far, the best information on the web about SAMD clocks.  I know because I've read everything out there and still have a problem with a SAMD0914A chip.  The chip is on a custom board of my design, and the chip is working fine and doing everything I've programmed it to do except there is no I2C output on the I2C pins.  After hours and hours of troubleshooting, I now believe that the problem is probably only that the peripheral clock is not configured properly to drive the I2C output.  I'm using the SAMD09 as an I2C Master, and I'm using Atmel's (Microchip's) I2C code.  Unfortunately, the documentation of that code doesn't say anything about the chip clocks, so it occurred to me a moment ago that the problem is likely that the code is OK but the clock isn't configured.  Do you happen to have an example of known-good config code.  I believe the task is to route and configure a clock for SERCOM0.  I've lost my mind chasing through half-complete Atmel documentation, so please understand my frustration and request for some help.  Best regards,  Damon

**Comment by theacodes** [comment]
Hi Damon,

You can take a look at Gemini's i2c implementation, perhaps that'll be helpful: https://github.com/theacodes/Winterbloom_Castor_and_Pollux/blob/main/firmware/src/hw/gem_i2c.c
