### ISSUE TITLE
Link to typefaces post is broken 

### ISSUE THREAD

**Issue by nkruglikov** [theacodes/blog.thea.codes#7]
Hello!

I am subscribed to you via RSS. The new post I received yesterday, titled “A few of my favourite typefaces”, is a 404 page, linked to  https://blog.thea.codes/typefaces-i-love

The same link is used on the main page.

**Comment by theacodes** [comment]
Oh no, that's a mistake. That post isn't ready yet. I'll get that fixed

**Comment by nkruglikov** [comment]
Thank you! Don't forget to post it to RSS again, please: the title looks interesting, I like both code and fonts :)

**Comment by theacodes** [comment]
Of course!
