### ISSUE TITLE
SAMD21_USART CALLBACK

### ISSUE THREAD

**Issue by Jeffin28** [theacodes/blog.thea.codes#8]
I did see your few articles based on SAMD21. I need your little bit of support on the SAMD21 usart CALLBACK code setup for both read and write. I tried the example code from Atmel studio 7, but it didnt give me an exact way of reception(RX) when I give data input via the serial window (Hercules/putty). I need to get the data with less than 8 characters, but the current example code only outputs when the input data have at least 8 characters.

Current scenario :

when i give "ABC"              (3 chara)              --> No output
when I give "ABCDEFGH"   (8 chara)              --> It will get print   

Requirement : 

I need to get the data whether it is less than or more than or equal to 8 characters when an interrupt occurs, that's my need here, what do you think? and what change should I do to the code to make that output?

Code : 

#include <asf.h>
#include <stdio.h>

void usart_read_callback(struct usart_module *const usart_module);
void usart_write_callback(struct usart_module *const usart_module);

void configure_usart(void);
void configure_usart_callbacks(void);

struct usart_module usart_instance;

#define MAX_RX_BUFFER_LENGTH   5

volatile uint8_t rx_buffer[MAX_RX_BUFFER_LENGTH];

void usart_read_callback(struct usart_module *const usart_module)
{
	usart_write_buffer_job(&usart_instance,
			(uint8_t *)rx_buffer, MAX_RX_BUFFER_LENGTH);
}

void usart_write_callback(struct usart_module *const usart_module)
{
	port_pin_toggle_output_level(LED_0_PIN);
}

void configure_usart(void)
{

	struct usart_config config_usart;

	usart_get_config_defaults(&config_usart);

	config_usart.baudrate    = 9600;
	config_usart.mux_setting = EDBG_CDC_SERCOM_MUX_SETTING;
	config_usart.pinmux_pad0 = EDBG_CDC_SERCOM_PINMUX_PAD0;
	config_usart.pinmux_pad1 = EDBG_CDC_SERCOM_PINMUX_PAD1;
	config_usart.pinmux_pad2 = EDBG_CDC_SERCOM_PINMUX_PAD2;
	config_usart.pinmux_pad3 = EDBG_CDC_SERCOM_PINMUX_PAD3;

	while (usart_init(&usart_instance,
	EDBG_CDC_MODULE, &config_usart) != STATUS_OK) {
        }
	usart_enable(&usart_instance);

}

void configure_usart_callbacks(void)
{
	usart_register_callback(&usart_instance,
			usart_write_callback, USART_CALLBACK_BUFFER_TRANSMITTED);
	usart_register_callback(&usart_instance,
			usart_read_callback, USART_CALLBACK_BUFFER_RECEIVED);

	usart_enable_callback(&usart_instance, USART_CALLBACK_BUFFER_TRANSMITTED);
	usart_enable_callback(&usart_instance, USART_CALLBACK_BUFFER_RECEIVED);
}

int main(void)
{
	system_init();
	configure_usart();
	configure_usart_callbacks();

	system_interrupt_enable_global();

	uint8_t string[] = "Hello World!\r\n";
	usart_write_buffer_wait(&usart_instance, string, sizeof(string));

	while (true) {

		usart_read_buffer_job(&usart_instance,
				(uint8_t *)rx_buffer, MAX_RX_BUFFER_LENGTH);
	}
}

**Comment by theacodes** [comment]
Hi @Jeffin28, I don't use ASF4 and I'm not generally available for support. I'd recommend reaching out to Microchip.
